apiVersion: v1
kind: Secret
metadata:
  name: env-vars
type: Opaque
stringData:
  zone_id: {{ .Values.route53_zone_id }}
  aws_key: {{ .Values.aws_key }}
  aws_secret: {{ .Values.aws_secret }}
  aws_region: {{ .Values.aws_region }}
  host_name: {{ .Values.host_name }}