name: "Build and Deploy to Kubernetes Cluster"

# triggers
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  image_build_publish:
    name: "Build and publish image to Dockerhub"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Docker Build and Publish"
        env:
          DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
          DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}
        run: |
          echo "Working Directory"
          pwd
          echo "Directory Contents"
          ls -alr
          echo "Dockerhub user: ${DOCKERHUB_USER}"
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PWD
          docker build -t $DOCKERHUB_USER/dns_beacon -f deploy/Dockerfile .
          docker push $DOCKERHUB_USER/dns_beacon

  chart_build_publish:
    name: "Build and publish chart to Dockerhub"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install helm
        run: sudo snap install helm --classic
      - name: "Package and publish"
        env:
          DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
          DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}
        run: |
          echo "hello world"
          helm version
          helm package deploy/dns_beacon_chart
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PWD
          helm push dns_beacon-1.0.0.tgz  oci://registry-1.docker.io/${DOCKERHUB_USER}
