name: "Build and Deploy to Kubernetes Cluster"

# triggers
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  image_build_publish:
    name: "Build and publish image to Dockerhub"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Make script executable"
        run: chmod +x ./.github/workflows/build-deploy.yml
      - name: "Docker Build and Publish"
        run: ./.github/workflows/build-deploy.yml
